// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Cdf15JPt_yZswEHDzHdtNWLKqJAcO2E',
    appId: '1:501819933249:web:e322ad4cc8838325097cc0',
    messagingSenderId: '501819933249',
    projectId: 'splitsmart-app-test1',
    authDomain: 'splitsmart-app-test1.firebaseapp.com',
    storageBucket: 'splitsmart-app-test1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GUQpDG3Ekmq78h3GutlgNywi9uhb6l8',
    appId: '1:501819933249:android:1e2dce4592068037097cc0',
    messagingSenderId: '501819933249',
    projectId: 'splitsmart-app-test1',
    storageBucket: 'splitsmart-app-test1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBg0GK44IspdCVBTTLv9ongatuuIEds48',
    appId: '1:501819933249:ios:f01e49870d188825097cc0',
    messagingSenderId: '501819933249',
    projectId: 'splitsmart-app-test1',
    storageBucket: 'splitsmart-app-test1.firebasestorage.app',
    androidClientId: '501819933249-0alf7kn1ua4arpeva5o2991006d57c2e.apps.googleusercontent.com',
    iosClientId: '501819933249-cfoks67i02lg1jgr0i5517glb5s7bo13.apps.googleusercontent.com',
    iosBundleId: 'com.splitsmart.splitsmart',
  );

}